config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "flats#index"
  resources :flats
  post "/search", to: "flats#search"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController

  def index
    @flats = Flat.all
  end

  def show
    @flat = Flat.find(params[:id])
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    @flat.save
    redirect_to flat_path(@flat)
  end

  def edit
    @flat = Flat.find(params[:id])
  end

  def update
    @flat = Flat.find(params[:id])
    @flat.update(flat_params)
    redirect_to flat_path(@flat)
  end

  def destroy
    @flat = Flat.find(params[:id])
    @flat.destroy
    redirect_to flats_path, status: :see_other
  end

  def search
    @flats = Flat.where("name LIKE ?", "%#{params[:query]}%")
    render :index
  end

  private

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests, :image_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/_form.html.erb
<div class="container mt-3">
  <%= simple_form_for @flat do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :description %>
    <%= f.input :price_per_night %>
    <%= f.input :image_url %>
    <%= f.input :number_of_guests %>
    <%= f.submit%>
  <% end %>
</div>

app/views/flats/edit.html.erb
<%=  render "form", flat: @flat %>

app/views/flats/index.html.erb
<div class="container mt-3">
  <div class="row">
    <div class="col-12">
      <h1>All flats (<%= @flats.size%>)</h1>
    </div>
  </div>
  <div class="row">
    <div class="col">
    <p> All <%= @flats.size%> flats </p>
    </div>
  </div>
  <div class="row">
    <% @flats.each do |flat| %>
      <div class="col-4">
        <div class="card mb-3">
          <div class="flat-show-card" style="background-color: #F8F9FA;">
            <div class="card-image" style="background-image: url(<%=flat.image_url%>)"></div>
            <h5 class="card-title p-2"><%= flat.name %></h5>
            <p class="card-text px-3"><%= flat.address %></p>
            <div class="d-flex flex-row">
              <p class="card-text px-3"><%= flat.price_per_night %> <i class="fa-solid fa-euro-sign"></i></i></p>
              <p class="card-text px-3"><%= flat.number_of_guests %> <i class="fa-solid fa-users"></i></p>
            </div>
          </div>
          <div class="m-2">
            <%= link_to "More info", flat_path(flat) %>
            <%= link_to "Edit", edit_flat_path(flat), class: "link-warning" %>
            <%= link_to "Delete", flat_path(flat), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "link-danger" %>
          </div>

        </div>
      </div>
    <% end %>

  </div>
</div>

app/views/flats/new.html.erb
<%= render "form", flat: @flat %>

app/views/flats/show.html.erb
<div class="map" style="height: 350px; background-image: url(<%=@flat.image_url %>)">

</div>
<div class="container margin-top-negative">
  <div class="row">
    <div class="col-8">
      <div class="flat-show-card">
        <%= @flat.name %>
        <%= @flat.address %>
      </div>
      <div class="flat-show-card">
        <h2>A bit more about this flat...</h2>
        <%= @flat.description %>
        <div class="map" style="height: 350px;"></div>
      </div>
    </div>
    <div class="col-4">
      <div class="flat-show-card">
        <form action>
          <div class="input-group mb-3">
            <span class="input-group-text" id="start-date-label">From</span>
            <input type="text" class="form-control" placeholder="<%=Date.current%>">
          </div>
          <div class="input-group mb-3">
            <span class="input-group-text" id="end-date-label">To</span>
            <input type="text" class="form-control" placeholder="<%=Date.current%>">
          </div>
          <div class="btn btn-success" style="width: 100%;">Book</div>
        </form>
      </div>

      <div class="flat-show-card">
        <h2>Details</h2>
        <p><%= @flat.number_of_guests %> people <%= @flat.price_per_night %>€</p>
      </div>
      <div class="flat-show-card">
        <div class="d-flex flex-row justify-content-between">
          <div>
            <p>Share</p>
          </div>
          <div>
            <i class="fa-brands fa-facebook-square me-2"></i>
            <i class="fa-brands fa-twitter-square me-2"></i>
            <i class="fa-brands fa-pinterest-square me-2"></i>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>

  <body>
  <%= render "/shared/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to "Simple AirBnb", root_path, class: "navbar-brand" %>
    <div class="d-flex flex-row">
      <form class="row row-cols-lg-auto g-3 align-items-center me-1" action="/search" method="post" data-turbo="false">
        <div class="col">
            <input type="text" name="query" class="form-control" id="query">
            <input hidden name="authenticity_token" value="<%= form_authenticity_token %>">
        </div>
        <div class="col">
          <button type="submit" class="btn btn-success">Search</button>
        </div>
      </form>
      <div class="btn btn-outline-primary my-2">
        <%= link_to "Add a flat", new_flat_path %>
      </div>
    </div>
  </div>
</nav>